version: "3.5"

services:
#  mysql:
#    image: mysql:8.3.0
#     # If you are a user of Apple silicon M1 chip, uncomment platform setting
#    platform: linux/amd64
#    volumes:
#      - /opt/homebrew/var/lib/mysql:/var/lib/mysql:cached
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: "link_identity"
  postgres:
    image: postgres:13
    # If you are a user of Apple silicon M1 chip, uncomment the platform setting
    platform: linux/amd64
    volumes:
      - /opt/homebrew/var/lib/postgres:/var/lib/postgresql/data:cached
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: link_identity
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
