# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DATABASE_NAME: "link_identity"
      DATABASE_HOST: "root"
      DATABASE_USERNAME: "root"
      DATABASE_PASS: "root"
      DATABASE_PORT: "5432"
      SERVER_PORT: "8000"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.6'  # Specify the version of Go.

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build ./...

      - name: Lint
        run: make lint-full

      - name: Run unittests
        run: go test ./...
